sudo: required
dist: trusty

language: go

env:
  DOCKER_COMPOSE_VERSION: 1.7.1

services:
  - docker

before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf 
